# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network :forwarded_port, guest: 1337, host: 31337
  config.vm.synced_folder "~/repos/", "/repos"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "file", source: "vmfs-http-sync.init", destination: "vmfs-http-sync.conf"
  config.vm.provision "file", source: "docker", destination: "docker"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git
    sudo apt-get install -y nodejs
    sudo ln -s /usr/bin/nodejs /usr/bin/node
    sudo -u root bash -c 'curl -L https://npmjs.org/install.sh | sh'
    git clone https://github.com/elsix/vmfs-http-sync.git
    cd vmfs-http-sync/ && sudo npm install -g

    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    sudo bash -c "echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list"
    sudo apt-get update
    sudo apt-get install -y linux-image-extra-$(uname -r)
    sudo apt-get install -y docker-engine
    sudo bash -c 'curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose'
    sudo chmod +x /usr/local/bin/docker-compose

    sudo bash -c "cp /home/vagrant/vmfs-http-sync.conf /etc/init/vmfs-http-sync.conf"
    sudo service vmfs-http-sync start
    while [[ `curl --max-time 1 -s -o /dev/null -w "%{http_code}" http://127.0.0.1:50080/status` -ne "200" ]]; do echo 'waiting for vmfs-http-sync'; sleep 1; done

    sudo bash -c "cd /home/vagrant/docker/envs/ && docker-compose -f dev.yml build && docker-compose -f dev.yml -p app up -d"
  SHELL
end

