# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  # Defines a private host network so we can expose whatever port we need from the virtual machine
  config.vm.network "private_network", type: "dhcp", netmask: "255.255.0.0"
  config.vm.network :forwarded_port, guest: 50080, host: 50080
  config.vm.synced_folder "~/repos/", "/repos"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "file", source: "../vmfsconf/vmfs-http-sync.init", destination: "vmfs-http-sync.conf"
  config.vm.provision "shell", inline: <<-SHELL
    # Mounting repos on boot
    sudo bash -c 'echo "vboxsf" >> /etc/initramfs-tools/modules'
    sudo bash -c 'update-initramfs -u'
    sudo bash -c 'echo "repos                   /repos   vboxsf defaults        0 0" >> /etc/fstab'

    # Installing needed software
    sudo -u root bash -c 'curl -sL https://deb.nodesource.com/setup | sudo bash -'
    sudo apt-get update

    # Preparing vmfs-http-sync tool
    sudo apt-get install -y git
    sudo apt-get install -y nodejs
    sudo ln -s /usr/bin/nodejs /usr/bin/node
    sudo -u root bash -c 'curl -L https://npmjs.org/install.sh | sh'
    git clone https://github.com/elsix/vmfs-http-sync.git
    cd vmfs-http-sync/ && sudo npm install -g
    sudo bash -c "cp /home/vagrant/vmfs-http-sync.conf /etc/init/vmfs-http-sync.conf"
    sudo service vmfs-http-sync start
    # Wating for vmfs-http-sync server to start
    while [[ `curl --max-time 1 -s -o /dev/null -w "%{http_code}" http://127.0.0.1:50080/status` -ne "200" ]]; do echo 'waiting for vmfs-http-sync'; sleep 1; done

    # Instaling missing application requirements
    sudo apt-get install -y nginx mongodb-server git
    sudo npm install -g bower
    sudo npm install -g sails
  SHELL
end
