web:
  build: ../images/
  dockerfile: nodejs
  command: /bin/bash
  hostname: web
  volumes:
    - '/repos_local/angular-jointjs-graph-demo/:/app'
  ports:
   - "1337:1337"
  links:
   - 'db:db'
  tty: true
db:
  build: ../images/
  dockerfile: mongo
  command: mongod
  hostname: db
  tty: true

